version: '3.7'
services:
  mariadb:
    image: 'mariadb:11.2'
    environment:
      - 'MARIADB_DATABASE=${mariadb_database}'
      - 'MARIADB_PASSWORD=${mariadb_user_password}'
      - 'MARIADB_ROOT_PASSWORD=${flyway_user_password}'
      - 'MARIADB_USER=${mariadb_user}'
    ports:
      - '3306:3306'
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge