spring:
  application:
    name: airqualityhome-server

  datasource:
    url: ${mariaDB_url}
    username: ${mariaDB_user}
    password: ${mariaDB_user_password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

airqualityhome:
  jwt-secret: ${jwt_secret}
  sensor-api-token-header-name: ${sensor_api_token_header_name}
  sensor-api-auth-token: ${sensor_api_auth_token}
  token-expire-millis: 300000 # 5 Minutes
  max-notification-interval-minutes: 30
  max-sensor-measurement-interval-minutes: 10
  vapid-public-key: ${vapid_public_key}
  vapid-private-key: ${vapid_private_key}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]