scrape_configs:
  - job_name: 'AirQualityHome-Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'AirQualityHome'
    basic_auth:
      username: 'user'
      password: 's3cret!'